version: '2'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:4.7.1
    container_name: wordpress-svc
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
 #     - ./config:/opt/config
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: p4ssw0rd!
      WORDPRESS_DEBUG: 1
#    command: /bin/sh -c "cat /opt/config/debug.php >> wp-config.php && /entrypoint.sh" 
    ports:
      - 80:80
      - 443:443
    networks:
      - back
  db:
    image: mysql:5.7
    container_name: mysql-svc
    restart: always
    volumes:
       - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-svc
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - back
networks:
  back:
volumes:
  db_data: